## Import packages!

In [1]:
import numpy as np
import astropy.constants as const
import astropy.units as u
from cosmolopy import constants
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import barnes_hut as bh
%matplotlib inline
%matplotlib notebook

## Load data files containing initial positions of galaxies.

In [2]:
galaxy_init = 'galaxies0.npy'
galaxy_step = 'galaxies1.npy'
gal_past = np.load(galaxy_init)
gal_current = np.load(galaxy_step)

## Evolve the galaxy cluster!

In [ ]:
num_steps = 10000

for i in range(0, num_steps):
    
    ## Calculate the acceleration of each galaxy.
    accel = bh.calc_accel(gal_current, np.full(len(gal_current), 1e12))
    
    ## Update the positions of each galaxy.
    pos = bh.calc_position(gal_current, gal_past, accel)
    
    ## The current timestep will become the n-1 timestep.
    gal_past = gal_current
    
    ## The updated position will become the n timestep.
    gal_current = pos
    
    ## Every 100 iterations, output a plot of the data and the 
    ## positional data for post processing.
    if i % 100 == 0:
        fig = plt.figure()
        ax = fig.add_subplot(111, projection = '3d')
        ax.set_xlim(0,13)
        ax.set_zlim(0,13)
        ax.set_ylim(0,13)
        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_zlabel('Z')
        plt.tight_layout()
        ax.plot(gal_current[:,0], gal_current[:,1], gal_current[:,2], '.',color='k')
        plt.savefig('plots/galaxies_%06d.png' % i)
        
        np.savetxt('plots/galaxy_pos_%06d.txt' % i, gal_current)
        
        print(i)

In [3]:
gal_past[0]

array([2.10404731, 0.01458301, 7.23985767])

In [4]:
gal_current[0]

array([2.10404747, 0.01458291, 7.23985767])

In [7]:
np.max(np.subtract(gal_past, gal_current), axis=0)

array([1.99899490e-07, 1.99818015e-07, 4.44089210e-16])